### ISSUE TITLE
Some extra ideas: new features

### ISSUE THREAD

**Issue by Dx-wmc** [moshi4/pyGenomeViz#14]
Hi, thank you very much for developing such wonderful software. In fact, I have been using genoplotR before and recently came across pyGenomeViz, which I find very useful as well. About this software, after going through the tutorial, I have some ideas to propose that could be considered as additional features: 
1. Can it support custom graphics? The pentagon shape provided by the author is similar to gggenes, but the resulting effect is not aesthetically pleasing when genes are small. 
2. Can it support the input of blast files? Actually, genoplotR can directly read blast results, but I couldn't find an import function here. 
3. Can it support the input of custom files such as tab files? 
4. It seems gene names cannot be directly read from GenBank files? 
These are some suggestions I would like to put forward and hope that you will give them some consideration. Thank you very much for developing this software.

**Comment by moshi4** [comment]
> 1\. Can it support custom graphics? The pentagon shape provided by the author is similar to gggenes, but the resulting effect is not aesthetically pleasing when genes are small.

What specific shapes do you expect custom graphics to have?
Also, even if the gene size is small, I do not know how one can create what is an aesthetically pleasing figure. I don't see any problem with it as it is now.

> 2\. Can it support the input of blast files? Actually, genoplotR can directly read blast results, but I couldn't find an import function here.

You want to be able to automatically generate similarity links from Blast files, correct?
Generating similarity links from Blast files is easily done with a few lines of code, so I honestly don't see much need for it personally.

> 3\. Can it support the input of custom files such as tab files?

GFF files are commonly used as TSV format files to store genes and their coordinate data, and since I have already implemented a gene visualization function from GFF files, I do not feel the need to add a visualization function from newly defined custom TSV files.

> 4\. It seems gene names cannot be directly read from GenBank files?

Visualization examples of gene id, gene name, product name, etc. from Genbank files are shown in the following document.
https://moshi4.github.io/pyGenomeViz/api-examples/practical_example/
Also, if you understand how to use BioPython's SeqFeature class, you should be able to freely obtain various information in Genbank files.

> The link is usually generated by blast alignment. How should we handle the situation when manually using reverse complementary sequences to blast against other sequences and generate links? The situation becomes even more complicated after using range in Genbank. xlims introduced in genoplotR can solve such problems, but pyGenomeviz has not considered this situation yet. This is also the problem I am currently facing.
>
> :information_source: I will answer the questions you raised in other issue here.

This implementation may be somewhat cumbersome.
For such users, I provide a CLI workflow for visualization of multi-genome comparison results, such as [pgv-mummer](https://moshi4.github.io/pyGenomeViz/cli-docs/pgv-mummer/). pgv-mummer also allows comparison visualization of partial and reverse complementary sequences, so it may be better to use this.

**Comment by Dx-wmc** [comment]
Thank you for your patient response. Recently, I have been trying to use the web program pyGenoemviz. For someone who usually writes code, this undoubtedly simplifies some operations and allows for intuitive comparison of results. However, I found that it seems to not support changing the order of comparison sequences. Is there any plan to add this feature?

**Comment by moshi4** [comment]
Users can change the order of genome comparisons by changing the file upload order.

**Comment by Dx-wmc** [comment]
> 用户可以通过更改文件上传顺序来更改基因组比较的顺序。

However, it is not convenient to run mmuer every time like this. If possible, it may be a good choice to add a serial number for each input file and then change the order. Of course, this is based on your availability and willingness to make additions.

**Comment by moshi4** [comment]
pyGenomeViz uses the [streamlit](https://github.com/streamlit/streamlit) web framework to build web apps.
Streamlit has various limitations in exchange for easy web app development with short code.
I personally think it would be difficult to implement the features you are proposing within these limitations.
