### ISSUE TITLE
Visualization using fasta file

### ISSUE THREAD

**Issue by amara86** [moshi4/pyGenomeViz#45]
Hi
Does pyGenomeViz supports fasta input or delta/coord file generated through nucmer packagae? What if we want to compare newly generated assemblies that are not yet annotated?

**Comment by moshi4** [comment]
Hi @amara86,

Try using the pyGenomeViz API as in the example below. This should make it easy to plot genome comparison results in fasta file format.

**Code Example**

[examples.zip](https://github.com/user-attachments/files/15803057/examples.zip)

```python
from pygenomeviz import GenomeViz
from pygenomeviz.align import MUMmer
from pygenomeviz.utils import ColorCycler
from pathlib import Path
from Bio import SeqIO
ColorCycler.set_cmap("tab10")

# Set your fasta files here
fasta_files = sorted(Path("./examples").glob("*.fna"))

# Initialize GenomeViz
gv = GenomeViz(feature_track_ratio=0.10)
gv.set_scale_bar()

for fasta_file in fasta_files:
    # Extract seqid & seq length in fasta
    records = list(SeqIO.parse(fasta_file, "fasta"))
    seqid2size = {str(rec.id): len(rec.seq) for rec in records}

    # Plot segment symbol feature
    track_name = Path(fasta_file).stem
    color = ColorCycler()
    track = gv.add_feature_track(track_name, seqid2size, label_kws=dict(color=color))
    for segment in track.segments:
        segment.add_feature(segment.start, segment.end, plotstyle="bigrbox", fc=color, lw=0.5)

# Run MUMmer alignment
align_coords = MUMmer(fasta_files).run()

# Plot MUMmer alignment links
if len(align_coords) > 0:
    min_ident = int(min([ac.identity for ac in align_coords if ac.identity]))
    color, inverted_color = "grey", "red"
    for ac in align_coords:
        gv.add_link(ac.query_link, ac.ref_link, color=color, inverted_color=inverted_color, v=ac.identity, vmin=min_ident)
    gv.set_colorbar([color, inverted_color], vmin=min_ident)

fig = gv.plotfig()
fig.savefig("result.png")
```

**result.png**

![result](https://github.com/moshi4/pyGenomeViz/assets/41852815/49cad6e0-fcbb-4e4c-8d42-2bfb74aaaba2)

**Comment by ckeeling** [comment]
I have the same question, but I am wondering how to change this suggested code for using BLAST (BLASTn and/or tBLASTn) instead of MUMmer?

In your example [GenBank comparison by BLAST](https://github.com/moshi4/pyGenomeViz?tab=readme-ov-file#genbank-comparison-by-blast) you include:
```
# Run BLAST alignment & filter by user-defined threshold
align_coords = Blast(gbk_list, seqtype="protein").run() # (I would change gbk_list to fasta_files)
align_coords = AlignCoord.filter(align_coords, length_thr=100, identity_thr=30)
```
Is this all we would need to change in your above code instead of:
```
# Run MUMmer alignment
align_coords = MUMmer(fasta_files).run()
```
 It seems that ```seqtype``` can only be ```protein``` or ```nucleotide```. If given nucleotide FASTA files, will using ```protein``` do a tBLASTn, or is it assuming a protein FASTA file?  I tried MUMmer, but the result wasn't as "clean" as I had hoped. Is there a way to "tune" the align_coords from MUMmer with AlignCoord.filter like you show with BLAST?

Thanks!
Chris
