### ISSUE TITLE
Pseudogene arrows are not plotted in pgv-mummer

### ISSUE THREAD

**Issue by kneubehl** [moshi4/pyGenomeViz#7]
Hello,

Awesome tool! I am using pgv-mummer v0.3.0 and I am noticing that the pseudogenes are not being plotted with arrows. The alignments for those regions are being plotted but there are no arrows present to represent where that "CDS" would be. Not sure if there is a setting I need to change but I suspect this would be with how the genbank files are read in and handled. Any guidance would be appreciated. Thanks!

-Alex

**Comment by moshi4** [comment]
Hi, @kneubehl

`pgv-mummer` (and `pgv-mmseqs`) only plots CDS features that have a *translation* qualifier in the Genbank file.
Therefore, as you pointed out, CDS features of pseudogenes without *translation* qualifiers are not plotted.

I will consider how to handle the plotting of pseudogenes. Please wait a moment.

**Comment by moshi4** [comment]
### Note for myself

Pseudogene of the CDS feature is excluded in the `extract_features()` method of the `Genbank` parser class.

https://github.com/moshi4/pyGenomeViz/blob/617caa6d0cf0defed4bf6faf957c1fd990e825d1/src/pygenomeviz/parser/genbank.py#L253-L257

**Comment by kneubehl** [comment]
If MUMmer is using protein sequences it will be kinda messy to use the pseudogene translations. I was initially operating under the assumption that the pgv-mummer was using nucleotide sequence. But I am noticing differences between the nucleotide and protein-based results. Seems to be at the edges of the genbank sequence. I included in the example picture the command I used. This is an example of how the 5' and 3' terminal CDS should have links between both sequences but there are no links in the protein default seqtype but there is when nucleotide is used as the seqtype option. 
![pygenomeviz_issue](https://user-images.githubusercontent.com/58899964/202085241-92daafed-cce9-490c-8a1b-e996b22d7fce.jpg)

**Comment by moshi4** [comment]
Sorry for the delay in answering.

> (1) differences between nucleotide and protein-based results

MUMMer uses the `nucmer` program for nucleotide-level sequence comparison and the `promer` program for protein-level (6 reading frame translation) comparison. Since `nucmer` and `promer` use different algorithms for comparison, there are naturally some differences in comparison results.

This problem comes from MUMmer, so it is honestly difficult for me to solve the problem.
It may be possible to reduce the differences in comparison results by adjusting the detailed parameters of MUMmer, but it is a bit troublesome to implement such a function.

> (2) linkages between sequences that do not match up with a CDS (there is a pseudogene there so no arrow but still a linkage)

The newly released pyGenomeViz v0.3.1 solves this problem by using the `--pseudo` option. It is also possible to change the color with the `--pseudo_color` option.

Below is an example of comparison visualization with and without pseudogene in E.coli using pgv-mummer.

**1. Disable --pseudo option**
```
pgv-download-dataset -n escherichia_coli
pgv-mummer --gbk_resources NC_000913.gbk:235000-265000 NC_002695.gbk:270000-300000 \
-o ecoli_no_pseudo --feature_plotstyle arrow --link_track_ratio 3.0
```
![result](https://user-images.githubusercontent.com/41852815/202895773-eec122a0-ee63-4c19-970d-c362e3f1d5b1.png)

**2. Enable --pseudo option**
```
pgv-download-dataset -n escherichia_coli
pgv-mummer --gbk_resources NC_000913.gbk:235000-265000 NC_002695.gbk:270000-300000 \
-o ecoli_pseudo --feature_plotstyle arrow --link_track_ratio 3.0 --pseudo
```
![result](https://user-images.githubusercontent.com/41852815/202895782-7ff767aa-7657-4a8d-a96b-409ac744c8f2.png)

**Comment by kneubehl** [comment]
Thanks for adding the --pseudo option! I looked into those genes that are different between the nucleotide and protein (issue 1 in the previous message). Those proteins on baBA2lp27 are 88% similar to a protein on bhDAHlp59 but they don't show up on the visualization or in the align_coords.csv. Do you think this is a problem with mummer? I can send you the genbank files if you want take a look.

**Comment by moshi4** [comment]
> Do you think this is a problem with mummer? 

Without seeing the data, it is difficult to determine the correct cause, but I think there are two possibilities.

1. **Simply not finding a matching sequence region**  
The sequence comparison by MUMmer(promer) 6 reading frame translation may not have been done properly in the target sequence region, and the link may not have been output.

2. **Target sequence region is excluded in the filtering stage**  
MUMmer provides a `delta-filter` tool to filter redundant comparison results with multiple overlaps, which is also used in pyGenomeViz. This `delta-filter` may be unexpectedly excluding target sequence regions.
